/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "timer.h"
#include "dac.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();
	int val = 0;
	DAC_Init();
	while(1)
	{
		START :
		while (val <= 4096)
		{
			DAC_SetValue(val);
			Timer_Init(20);
			while (!(timer_intr_flag))
				;
			val += 16;
			timer_intr_flag = 0;

			if (val == 4096)
				{
				while (val <= 4096)
					{
					DAC_SetValue(val);
					Timer_Init(20);
					while (!(timer_intr_flag))
									;
					val -= 16;
					timer_intr_flag = 0;
						if (val == 0)
							goto START;
					}
				}
		}
	}

	return 0;
}
