/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "uart.h"
#include <string.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
	char str[32];
	SystemInit();
	int choice;
	UartInit(9600);
	LedInit(LED_RED_PIN);
	LedInit(LED_BLUE_PIN);
	UartPuts("Hello\r\n");
	do
	{
	UartPuts("Menu\r\n");
	UartPuts("1. Red Led On\r\n");
	UartPuts("2. Red Led Off\r\n");
	UartPuts("3. Blue Led On\r\n");
	UartPuts("4. Blue Led Off\r\n");
	UartPuts("5.Exit\r\n");
	UartPuts("Your choice : \r\n");
	UartGets(str);
	sscanf(str,"%d", &choice);

	switch(choice)
	{
	case 1 : LedOn(LED_RED_PIN);
			break;
	case 2 : LedOff(LED_RED_PIN);
			break;
	case 3 : LedOn(LED_BLUE_PIN);
			break;
	case 4 : LedOff(LED_BLUE_PIN);
			break;
	case 5 : UartPuts("Bye Bye\r\n");
			break;
	}
	}while(choice != 5);

	return 0;

}





